// Code generated by GENERATOR. DO NOT EDIT.

import * as jspb from "google-protobuf"

import * as google_protobuf_duration_pb from 'google-protobuf/google/protobuf/duration_pb';
import * as gogoproto_gogo_pb from '../../../gogoproto/gogo_pb';

export class Status extends jspb.Message {
  getPhase(): Phase;
  setPhase(value: Phase): void;

  getState(): State;
  setState(value: State): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): Status.AsObject;
  static toObject(includeInstance: boolean, msg: Status): Status.AsObject;
  static serializeBinaryToWriter(message: Status, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): Status;
  static deserializeBinaryFromReader(message: Status, reader: jspb.BinaryReader): Status;
}

export namespace Status {
  export type AsObject = {
    phase: Phase,
    state: State,
  }
}

export class RetentionOptions extends jspb.Message {
  getRetainWindow(): google_protobuf_duration_pb.Duration | undefined;
  setRetainWindow(value?: google_protobuf_duration_pb.Duration): void;
  hasRetainWindow(): boolean;
  clearRetainWindow(): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): RetentionOptions.AsObject;
  static toObject(includeInstance: boolean, msg: RetentionOptions): RetentionOptions.AsObject;
  static serializeBinaryToWriter(message: RetentionOptions, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): RetentionOptions;
  static deserializeBinaryFromReader(message: RetentionOptions, reader: jspb.BinaryReader): RetentionOptions;
}

export namespace RetentionOptions {
  export type AsObject = {
    retainWindow?: google_protobuf_duration_pb.Duration.AsObject,
  }
}

export enum Phase { 
  MARK = 0,
  DELETE = 1,
}
export enum State { 
  PENDING = 0,
  RUNNING = 1,
  COMPLETE = 2,
}
